### ISSUE TITLE
Cannot postMessage via javascriptChannel with non-ascii characters (e.g. Chinese)

### ISSUE THREAD

**Issue by jlcool** [jakky1/webview_win_floating#29]
比如controller.addJavaScriptChannel("Flutter", callback:(message) {
      print("无法触发")
    });
页面中执行Flutter.postMessage("中文")
就会报错

报错内容：
```
FormatException: Missing extension byte (at offset 42)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1760:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:349:37)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:502:29)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
#4      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:529:39)
#5      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
#6      StandardMethodCodec.decodeMethodCall (package:flutter/src/services/message_codecs.dart:607:44)
#7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:569:35)
#8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564:34)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:581:35)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:347:15)
#11     _rootRun (dart:async/zone.dart:1399:13)
#12     _CustomZone.run (dart:async/zone.dart:1301:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#14     _invoke2 (dart:ui/hooks.dart:346:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
```
操作系统win11
在设置->时间和语言->语言和区域->管理语言设置->更改系统区域设置，选中里面的Beta版：使用Unicode UTF-8提供全球语言支持后不报错
不改设置插件能修复吗？

**Comment by jakky1** [comment]
Fixed.

Please try new version `2.2.8`

**Comment by jakky1** [comment]
Fixed.
Please try new version

Test code:
```dart
controller.addJavaScriptChannel("Flutter", onMessageReceived: (message) {
  print("js -> dart : ${message.message}");
});

controller.runJavaScript("Flutter.postMessage('Chinese 中文')");
```
